fix: correct asdf inclusion in $PATH
jenkins-infra/packer-images pull request #1043
Opened 2024-02-10 17:15 UTC by lemeurherve

This PR uses hardcoded path to include asdf in the $PATH so asdf installed tools like yq can be executed.

Note: there might be a way to keep this folder as a variable but as it breaks current uses this "easy" solution should be enough, can be revised in a following pull request.

Ref:
- #1042

2024-02-10 19:35 UTC, lemeurherve commented
On arm images `goss` seems to pick the `ruby` version installed by `vagrant` as one of its dependencies (3.0.2p107), while `asdf` is installing the version 2.6.10 **after** `vagrant` 🤔

(Search for "ruby" in https://infra.ci.jenkins.io/job/infra-tools/job/packer-images/job/PR-1043/2/pipeline-console/log?nodeId=120)

2024-02-10 21:58 UTC, timja approved these changes

2024-02-12 08:04 UTC, smerle33 requested changes
this doesn't correct the problem as seen here https://infra.ci.jenkins.io/job/infra-tools/job/packer-images/job/PR-1043/13/ 
but I think, point to why I cannot use the correct npm here https://github.com/jenkins-infra/helpdesk/issues/3823#issuecomment-1918841628

2024-02-12 08:25 UTC, dduportal commented
Please note that you will never get a universal solution as the `PATH` is governed by a LOT of different mechanisms (considering only Linux):

- Jenkins environment global setup (if any)
- Jenkins per-agent environment setup (if any) => usually only global agents
- Jenkins agent/cloud plugin environment setup (if any) => different between Azure VM, Kubernetes, Azure Container Instances, EC2, etc.
- Jenkins agent initialization method => inbound (relies on the agent process spawning method) or SSH (relies on the SSH server setup which **may** filter the `PATH`)
- Jenkins agent type => major differences between VMs (systemd load different environments) and containers (no `/etc/environment` loaded but image metadata are used to define environment)
- Shell used for the pipeline (global `bash`, local `bash`) => we enforce `/bin/bash` at Jenkins controller but it can be overloaded with the proper pipeline syntax
- Pipeline environment (`env.` groovy object and the `environement {}` /  `withEnv[] {}` blocks)
-

2024-02-12 08:26 UTC, dduportal commented on build-jenkins-agent-ubuntu.pkr.hcl
> +      "source /home/jenkins/.asdf/asdf.sh && asdf list", # Required as this is a non-interactive and non-login `bash`
Why `asdf list` ? Is it debug?

2024-02-12 09:06 UTC, lemeurherve commented on build-jenkins-agent-ubuntu.pkr.hcl
> +      "source /home/jenkins/.asdf/asdf.sh && asdf list", # Required as this is a non-interactive and non-login `bash`
Yes (cf commit msg)

2024-02-12 09:32 UTC, lemeurherve commented on provisioning/ubuntu-provision.sh
> +  sed -e '/^PATH/s/"$/:\/home\/jenkins\/.asdf\/shims:\/home\/jenkins\/.asdf\/bin\"/g' -i /etc/environment
```suggestion
  sed --regexp-extended "s|^PATH=(.*)"$|PATH=\1:${asdf_install_dir}/shims:${asdf_install_dir}/bin"|" -i /etc/environment
```
Result of mob programming with @smerle33 @dduportal

2024-02-12 09:44 UTC, lemeurherve commented on build-jenkins-agent-ubuntu.pkr.hcl
>        "goss --version",
```suggestion
      "echo $PATH && cat /etc/environment",
      "goss --version",
```
More debug

2024-02-12 10:09 UTC, lemeurherve commented on provisioning/ubuntu-provision.sh
> +  sed --regexp-extended "s|^PATH=(.*)"$|PATH=\1:${asdf_install_dir}/shims:${asdf_install_dir}/bin"|" -i /etc/environment
```suggestion
  sed --regexp-extended "s|^PATH=(.*)"$|PATH=\1:${asdf_install_dir}/shims:${asdf_install_dir}/bin"|" /etc/environment
```

> [2024-02-12T09:51:41.175Z] [1;31m2024-02-12T09:51:41Z: ==> docker.ubuntu: + sed --regexp-extended 's|^PATH=(.*)$'[0m
> [2024-02-12T09:51:41.175Z] [1;31m2024-02-12T09:51:41Z: ==> docker.ubuntu: + PATH='1:/home/jenkins/.asdf/shims:/home/jenkins/.asdf/bin|'[0m
> [2024-02-12T09:51:41.175Z] [1;31m2024-02-12T09:51:41Z: ==> docker.ubuntu: + -i /etc/environment[0m
> [2024-02-12T09:51:41.175Z] [1;31m2024-02-12T09:51:41Z: ==> docker.ubuntu: /tmp/script_8682.sh: line 159: -i: command not found[0m

2024-02-12 10:38 UTC, lemeurherve commented
@smerle33 @dduportal KO:

> 
> [2024-02-12T10:16:16.236Z] [1;31m2024-02-12T10:16:16Z: ==> azure-arm.ubuntu: + sed --regexp-extended 's|^PATH=(.*)$'[0m
> [2024-02-12T10:16:16.236Z] [1;31m2024-02-12T10:16:16Z: ==> azure-arm.ubuntu: + PATH='1:/home/jenkins/.asdf/shims:/home/jenkins/.asdf/bin|'[0m
> [2024-02-12T10:16:16.236Z] [1;31m2024-02-12T10:16:16Z: ==> azure-arm.ubuntu: + /etc/environment[0m
> [2024-02-12T10:16:16.236Z] [1;31m2024-02-12T10:16:16Z: ==> azure-arm.ubuntu: /tmp/script_60.sh: line 159: /etc/environment: Permission denied[0m
> [2024-02-12T10:16:16.236Z] [1;31m2024-02-12T10:16:16Z: ==> azure-arm.ubuntu: sed: -e expression #1, char 13: unterminated `s' command[0m

2024-02-13 09:13 UTC, lemeurherve commented on provisioning/ubuntu-provision.sh
> +  sed -R -E "s|^PATH=(.*)"$|PATH=\1:${asdf_install_dir}/shims:${asdf_install_dir}/bin"|" /etc/environment
```suggestion
  sed -R "s|^PATH=\(.*\)"$|PATH=\1:${asdf_install_dir}/shims:${asdf_install_dir}/bin"|" /etc/environment
```

2024-02-13 10:28 UTC, dduportal commented on provisioning/ubuntu-provision.sh
> +  sed --regexp-extended "s|^PATH=\(.*\)\"$|PATH=\1:${asdf_install_dir}/shims:${asdf_install_dir}/bin\"|" /etc/environment
```suggestion
  sed --in-place --regexp-extended "s|^PATH=(.*)\"|PATH=\1:${asdf_install_dir}/shims:${asdf_install_dir}/bin\"|g" /etc/environment
```

2024-02-13 10:35 UTC, dduportal commented on provisioning/ubuntu-provision.sh
> +  sed --regexp-extended "s|^PATH=\(.*\)\"$|PATH=\1:${asdf_install_dir}/shims:${asdf_install_dir}/bin\"|" /etc/environment
- Ref.: https://www.gnu.org/software/sed/manual/html_node/ERE-syntax.html , the `--regexp-extended` (same as `-r` and `-E`) means we must not escape special characters such as parenthesis (`(` / `)`) unless we want them literate. Our CI errors was due to no escape group in the search pattern: as such `\1` was unknown
- The `g` at the end of the sed argument has no influence: I've added it by reflex

2024-02-13 10:45 UTC, dduportal requested changes

2024-02-13 10:45 UTC, dduportal commented on build-jenkins-agent-ubuntu.pkr.hcl
> +    execute_command = "{{ .Vars }} sudo -E su - jenkins -c \"bash -eux '{{ .Path }}'\""
```suggestion
    execute_command = "{{ .Vars }} sudo -E su - jenkins -c \"bash -eu '{{ .Path }}'\""
```

2024-02-13 10:45 UTC, dduportal commented on build-jenkins-agent-ubuntu.pkr.hcl
> +      "source /home/jenkins/.asdf/asdf.sh && asdf list", # Required as this is a non-interactive and non-login `bash`
```suggestion
      "source /home/jenkins/.asdf/asdf.sh", # Required as this is a non-interactive and non-login `bash`
```

2024-02-13 10:45 UTC, dduportal commented on build-jenkins-agent-ubuntu.pkr.hcl
> +      "echo $PATH && cat /etc/environment",
```suggestion
```

2024-02-13 10:45 UTC, dduportal commented on provisioning/ubuntu-provision.sh
> +  sed --in-place --regexp-extended "s|^PATH=(.*)\"|PATH=\1:${asdf_install_dir}/shims:${asdf_install_dir}/bin\"|g" /etc/environment
```suggestion
  sed --in-place --regexp-extended "s|^PATH=(.*)\"$|PATH=\1:${asdf_install_dir}/shims:${asdf_install_dir}/bin\"|" /etc/environment
```

2024-02-13 14:41 UTC, smerle33 approved these changes

2024-02-13 14:41 UTC, dduportal approved these changes
Approving the PR, as we need to land the `/etc/environment` fix first before dealing with the `PATH` order of the installed ruby (package dependency of `vagrant`).

We'll update the goss test for `ruby` to only check for the presence of a ruby binary in the default PATH, not a specific version

2024-02-13 14:46 UTC, dduportal approved these changes

2024-02-13 16:42 UTC, merged