feat: add JDK21 version jdk21-2023-08-09-06-56-beta prerelease
jenkins-infra/packer-images pull request #769
Opened 2023-08-09 07:51 UTC by smerle33

as per https://github.com/jenkins-infra/helpdesk/issues/3709

2023-08-09 08:57 UTC, dduportal commented on provisioning/ubuntu-provision.sh
> +  mkdir -p /opt/jdk-8 /opt/jdk-11 /opt/jdk-17 /opt/jdk-19 /opt/jdk-21
```suggestion
  for jdkVersion in 8 11 17 19 21; do
    echo "/opt/jdk-$jdkVersion"
  done
```

(Nit)

2023-08-09 08:58 UTC, timja commented on provisioning/ubuntu-provision.sh
> +  mkdir -p /opt/jdk-8 /opt/jdk-11 /opt/jdk-17 /opt/jdk-19 /opt/jdk-21
echo?

2023-08-09 08:58 UTC, dduportal requested changes
Don't forget the Goss tests: https://github.com/jenkins-infra/packer-images/blob/f4b1666a0cea84411d473543579a980afe94d559/goss/goss.yaml#L2-L21

2023-08-09 18:28 UTC, lemeurherve approved these changes
🚀

2023-08-10 10:31 UTC, dduportal approved these changes
LGTM

2023-08-10 10:31 UTC, merged