Chore/auto update
jenkins-infra/packer-images pull request #82
Opened 2021-08-30 17:24 UTC by dduportal

2021-08-30 18:09 UTC, olblak commented on updatecli/updatecli.d/compose.yml
> +        kind: regex
It seems that https://github.com/docker/compose uses semantic versioning so something like seems easier to read

```suggestion
        kind: semver
        pattern: "~1"
```

2021-08-30 18:10 UTC, olblak commented on updatecli/updatecli.d/compose.yml
> +        kind: regex
```suggestion
        kind: semver
        pattern: "~1"
```

2021-08-30 18:10 UTC, olblak commented on updatecli/updatecli.d/compose.yml
> +        pattern: "^(\\d*).(\\d*).(\\d*)$"
```suggestion
```

2021-08-30 18:16 UTC, olblak commented on updatecli/updatecli.d/git-lfs.yml
> +        kind: regex
Same comment here, please be informed of this bug https://github.com/updatecli/updatecli/issues/244
the semver automatically remove the prefix "v" just before fetching changelogs

```suggestion
        kind: semver
```

2021-08-30 18:16 UTC, olblak commented on updatecli/updatecli.d/git-lfs.yml
> +        pattern: "^v(\\d*).(\\d*).(\\d*)$"
```suggestion
```

2021-08-30 18:16 UTC, olblak commented on updatecli/updatecli.d/git-lfs.yml
> +    transformers:
```suggestion
```

2021-08-30 18:17 UTC, olblak commented on updatecli/updatecli.d/git-lfs.yml
> +      - trimPrefix: "v"
Character 'v' is already remove in the semantic versioning
```suggestion
```

2021-08-30 18:18 UTC, olblak commented on updatecli/updatecli.d/git.yml
> +        kind: regex
```suggestion
        kind: semver
```

2021-08-30 18:19 UTC, olblak commented on updatecli/updatecli.d/git.yml
> +        pattern: "^v(\\d*).(\\d*).(\\d*)$"
```suggestion
```

2021-08-30 18:19 UTC, olblak commented on updatecli/updatecli.d/git.yml
> +    transformers:
```suggestion
```

2021-08-30 18:19 UTC, olblak commented on updatecli/updatecli.d/git.yml
> +      - trimPrefix: "v"
```suggestion
```

2021-08-30 18:22 UTC, olblak requested changes
Few minor suggestion which would  avoid relying on regex :D

2021-08-31 09:27 UTC, dduportal commented
- Taken @olblak review feedbacks
- Added jdk8 and jdk11 (as #78 is merged)
- Rebased from main branch

2021-09-16 08:16 UTC, dduportal commented
- Rebased on latest main branch (with Jenkins job migrated to infra.ci)
- Applied @timja proposal from #88 to enable release-drafter (paving the way for automatic release)
- Increased timeout and VM size for the Windows-2019 Azure VM as it seems sometime (until we find the real blocking issue that requires connecting to the instance, read the sysprep log and see what is going wrong)

2021-09-16 08:19 UTC, timja approved these changes

2021-09-16 09:13 UTC, merged

2021-09-16 09:14 UTC, dduportal commented
The Windows build on Azure is still blocked: since the rest passed successfully, I'm merging this