chore: adding asdf AND npm test in goss
jenkins-infra/packer-images pull request #836
Opened 2023-10-10 13:44 UTC by smerle33

as per https://github.com/jenkins-infra/helpdesk/issues/3763

2023-10-13 12:16 UTC, smerle33 commented
updatecli error due to chicken and egg : `ERROR: something went wrong in target "updateASDFVersionInGoss" : "couldn't find key \"$.command.asdf.stdout[0]\" from file \"goss/goss.yaml\""`
local test without `scmid: default` looks good : 
```
 Bump ASDF version:
        Source:
                ✔ [lastReleaseVersion] Get the latest ASDF version
        Target:
                ⚠ [updateASDFVersionInGoss] Update the ASDF version in the goss test
 ```

2023-10-16 10:04 UTC, dduportal commented on build-jenkins-agent-ubuntu.pkr.hcl
> +      "asdf version",
```suggestion
```

(sounds like a former debug step)

2023-10-16 10:05 UTC, dduportal commented on build-jenkins-agent-ubuntu.pkr.hcl
> +      "source /home/jenkins/.asdf/asdf.sh",
```suggestion
      "source /home/jenkins/.asdf/asdf.sh", # Required as this is a non-interactive and non-login `bash`
```

2023-10-16 10:06 UTC, dduportal requested changes
Good job 👍 

A few debug leftovers and a nitpick suggestion for a comment (only leftovers are required to be updated)

2023-10-17 05:33 UTC, dduportal approved these changes

2023-10-17 05:33 UTC, merged